spring:
  datasource:
    username: "root"
    password: "12345678"
    url: "jdbc:mysql://localhost:3306/product?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8"
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#        ddl-auto: none
    show-sql: true
#  redis:
#    host: localhost
#    port: 6379
#    client-type: jedis
#  cache:
#    redis:
#      time-to-live: 60000 # in milliseconds

